/* HP Fashion — catalogue data.
   One flat product list keeps filtering, search and the detail page honest:
   every page reads from the same source, nothing is duplicated in markup. */

const SECTIONS = [
  {
    slug: "men",
    label: "Men",
    heading: "Menswear",
    lede: "Shirting that holds a press, denim that earns its fade, and wedding pieces cut for a Coimbatore August.",
    hero: "images/edit-fold.jpg",
    heroAlt: "Folded grey and charcoal shirts stacked on a dark surface",
    varieties: [
      { slug: "shirts",   name: "Formal Shirts",      blurb: "Two-ply cottons, cut for the desk and the dinner after it." },
      { slug: "tees",     name: "T-Shirts",           blurb: "Combed cotton, honest weights, necklines that stay flat." },
      { slug: "denim",    name: "Denim & Trousers",   blurb: "From 14oz selvedge to a chino you can sit through a wedding in." },
      { slug: "ethnic",   name: "Ethnic & Wedding",   blurb: "Kurtas, bandhgalas and sherwanis, finished by hand in-house." },
      { slug: "layering", name: "Blazers & Jackets",  blurb: "Half-canvas tailoring in weights that work at 34°C." }
    ]
  },
  {
    slug: "women",
    label: "Women",
    heading: "Womenswear",
    lede: "Handloom sarees, everyday kurtas and bridal work that takes months — kept on the same rail, priced without theatre.",
    hero: "images/edit-grey-blazer.jpg",
    heroAlt: "A woman in a grey blazer and white skirt photographed outdoors",
    varieties: [
      { slug: "sarees",  name: "Sarees",             blurb: "Georgette, chiffon, cotton and silk — drape-tested before they reach the rail." },
      { slug: "kurti",   name: "Kurtis & Salwar Sets", blurb: "Breathable cottons for the week, chikankari for the weekend." },
      { slug: "dresses", name: "Dresses",            blurb: "Midis, slips and column cuts in white, ivory and stone." },
      { slug: "tops",    name: "Tops & Blouses",     blurb: "Poplin, satin and linen pieces that carry a whole wardrobe." },
      { slug: "bridal",  name: "Lehengas & Bridal",  blurb: "Zardozi, kanjivaram and temple-border work, made to measure." }
    ]
  },
  {
    slug: "kids",
    label: "Kids",
    heading: "Kidswear",
    lede: "Clothes sized 2 to 12 that survive a playground on Monday and a family function on Sunday.",
    hero: "images/edit-hangers.jpg",
    heroAlt: "A single wooden hanger on a white wall",
    varieties: [
      { slug: "boys",   name: "Boys' Shirts",     blurb: "Soft collars, real buttons, nothing that scratches." },
      { slug: "girls",  name: "Girls' Dresses",   blurb: "Frocks with room to twirl and pockets they will actually use." },
      { slug: "tees",   name: "Everyday T-Shirts", blurb: "Pre-shrunk cotton, washed forty times before we sold you one." },
      { slug: "ethnic", name: "Festive & Ethnic", blurb: "Pattu pavadai and kurta sets, lined so they never itch." },
      { slug: "winter", name: "Winterwear",       blurb: "Knits and light padding for Ooty weekends and December mornings." }
    ]
  }
];

const PRODUCTS = [
  /* ---------------------------------------------------------- MEN / SHIRTS */
  { id:"m-shirt-1", section:"men", variety:"shirts", name:"Meridian White Poplin", price:1690, mrp:2190, img:"images/m-shirt-1.jpg",
    alt:"Man wearing a crisp white poplin dress shirt",
    story:"The shirt we are judged on. 120s two-ply poplin, mother-of-pearl buttons, and a collar with a removable bone so it stands after the fourth wash.",
    spec:[["Fabric","120s two-ply cotton poplin"],["Fit","Slim, darted back"],["Collar","Semi-cutaway, removable bones"],["Care","Machine wash cold, press damp"]],
    colours:["Optic White","Pale Grey"], sizes:["S","M","L","XL","XXL"], tag:"Bestseller" },
  { id:"m-shirt-2", section:"men", variety:"shirts", name:"Harbour Blue Oxford", price:1490, mrp:1990, img:"images/m-shirt-2.jpg",
    alt:"Man in a blue oxford shirt and sunglasses",
    story:"Washed twice before it is folded, so the blue arrives already softened. Wear it under a blazer on Friday and untucked on Saturday.",
    spec:[["Fabric","Garment-washed cotton oxford"],["Fit","Regular"],["Collar","Button-down"],["Care","Machine wash cold, tumble low"]],
    colours:["Harbour Blue","White"], sizes:["S","M","L","XL","XXL"] },
  { id:"m-shirt-3", section:"men", variety:"shirts", name:"Weekday Chambray", price:1290, mrp:1690, img:"images/m-shirt-3.jpg",
    alt:"A blue button-up shirt laid flat on a white table",
    story:"Chambray with the hand of a worn-in favourite from day one. Our most forgiving shirt in a humid week.",
    spec:[["Fabric","Soft-touch cotton chambray"],["Fit","Regular"],["Collar","Point"],["Care","Machine wash cold"]],
    colours:["Chambray Blue","Slate"], sizes:["S","M","L","XL","XXL"] },
  { id:"m-shirt-4", section:"men", variety:"shirts", name:"Boardroom Twill", price:1890, mrp:2450, img:"images/m-shirt-4.jpg",
    alt:"Man in a blue dress shirt and black trousers standing indoors",
    story:"A dense twill that resists creasing through a full day of meetings, finished with a placket stiff enough to sit flat under a tie.",
    spec:[["Fabric","Compact-spun cotton twill"],["Fit","Slim"],["Collar","Spread"],["Care","Machine wash cold, warm iron"]],
    colours:["Steel","White","Charcoal"], sizes:["S","M","L","XL","XXL"] },
  { id:"m-shirt-5", section:"men", variety:"shirts", name:"Sunday Stripe", price:1590, mrp:2090, img:"images/m-shirt-5.jpg",
    alt:"Man in a blue and white striped shirt with black trousers",
    story:"Yarn-dyed stripes that will not fade to grey in the third summer. Cut a half-inch longer so it stays tucked.",
    spec:[["Fabric","Yarn-dyed cotton stripe"],["Fit","Regular"],["Collar","Semi-spread"],["Care","Machine wash cold, line dry"]],
    colours:["Blue Stripe","Grey Stripe"], sizes:["S","M","L","XL","XXL"] },

  /* ------------------------------------------------------------ MEN / TEES */
  { id:"m-tee-1", section:"men", variety:"tees", name:"Studio Crew, White", price:790, mrp:990, img:"images/m-tee-1.jpg",
    alt:"Man wearing a plain white crew neck t-shirt",
    story:"240 GSM combed cotton with a ribbed neck that does not go wavy. We sell more of this than anything else in the shop.",
    spec:[["Fabric","240 GSM combed cotton"],["Fit","Regular"],["Neck","1.5cm ribbed crew"],["Care","Machine wash cold, dry flat"]],
    colours:["White","Ash","Black"], sizes:["S","M","L","XL","XXL"], tag:"Bestseller" },
  { id:"m-tee-2", section:"men", variety:"tees", name:"Fade Teal Crew", price:890, mrp:1190, img:"images/m-tee-2.jpg",
    alt:"Man in a teal crew neck t-shirt wearing glasses",
    story:"Piece-dyed for a colour that shifts gently rather than patchily. Slightly shorter in the body for a cleaner tuck.",
    spec:[["Fabric","220 GSM ring-spun cotton"],["Fit","Regular"],["Neck","Ribbed crew"],["Care","Machine wash cold, inside out"]],
    colours:["Fade Teal","Fog Grey"], sizes:["S","M","L","XL"] },
  { id:"m-tee-3", section:"men", variety:"tees", name:"Everyday Heavy Tee", price:990, mrp:1290, img:"images/m-tee-3.jpg",
    alt:"Man in a white crew neck t-shirt outdoors",
    story:"Our heaviest cotton at 280 GSM. It hangs instead of clinging, which is the whole point in August.",
    spec:[["Fabric","280 GSM heavyweight cotton"],["Fit","Relaxed"],["Neck","Reinforced crew"],["Care","Machine wash cold"]],
    colours:["White","Stone","Charcoal"], sizes:["S","M","L","XL","XXL"] },
  { id:"m-tee-4", section:"men", variety:"tees", name:"Midnight Crew", price:690, mrp:890, img:"images/m-tee-4.jpg",
    alt:"Man wearing a black crew neck t-shirt",
    story:"Reactive-dyed black that stays black. The one to pack when you are travelling light.",
    spec:[["Fabric","200 GSM cotton jersey"],["Fit","Slim"],["Neck","Ribbed crew"],["Care","Wash cold with darks"]],
    colours:["Midnight","Graphite"], sizes:["S","M","L","XL"] },
  { id:"m-tee-5", section:"men", variety:"tees", name:"Pima Relaxed Tee", price:1190, mrp:1490, img:"images/m-tee-5.jpg",
    alt:"Man in a white relaxed-fit cotton t-shirt",
    story:"Long-staple pima with a faint sheen and almost no pilling. The tee for people who have given up on tees.",
    spec:[["Fabric","Peruvian pima cotton"],["Fit","Relaxed, dropped shoulder"],["Neck","Flat-lock crew"],["Care","Machine wash cold, dry flat"]],
    colours:["Ivory","Cloud Grey"], sizes:["S","M","L","XL","XXL"] },

  /* ----------------------------------------------------------- MEN / DENIM */
  { id:"m-denim-1", section:"men", variety:"denim", name:"Rigid Selvedge 14oz", price:2890, mrp:3590, img:"images/m-denim-1.jpg",
    alt:"Three pairs of denim jeans in assorted washes",
    story:"Raw 14oz selvedge on a shuttle loom. Stiff for a fortnight, then it becomes yours and nobody else's.",
    spec:[["Fabric","14oz raw selvedge denim"],["Fit","Straight"],["Rise","Mid"],["Care","Wash cold after 60 wears, hang dry"]],
    colours:["Raw Indigo"], sizes:["28","30","32","34","36","38"], tag:"Limited run" },
  { id:"m-denim-2", section:"men", variety:"denim", name:"Stone Wash Slim", price:2190, mrp:2790, img:"images/m-denim-2.jpg",
    alt:"A pair of light blue jeans on a white background",
    story:"Stone-washed with two per cent stretch, so the slim leg still lets you sit through a four-hour function.",
    spec:[["Fabric","12oz cotton with 2% elastane"],["Fit","Slim tapered"],["Rise","Mid"],["Care","Machine wash cold, inside out"]],
    colours:["Stone Blue"], sizes:["28","30","32","34","36"] },
  { id:"m-denim-3", section:"men", variety:"denim", name:"Indigo Straight", price:1990, mrp:2490, img:"images/m-denim-3.jpg",
    alt:"A stack of indigo denim jeans",
    story:"A plain, unbothered straight leg in mid indigo. No whiskering, no rips, nothing to date it.",
    spec:[["Fabric","12.5oz cotton denim"],["Fit","Straight"],["Rise","Mid"],["Care","Machine wash cold"]],
    colours:["Mid Indigo"], sizes:["28","30","32","34","36","38"] },
  { id:"m-denim-4", section:"men", variety:"denim", name:"Jet Black Tapered", price:2290, mrp:2890, img:"images/m-denim-4.jpg",
    alt:"Blue denim jeans photographed on a dark surface",
    story:"Overdyed twice for a black that survives thirty washes. Reads as trousers after six in the evening.",
    spec:[["Fabric","11oz overdyed denim"],["Fit","Tapered"],["Rise","Mid"],["Care","Wash cold, separately for first three washes"]],
    colours:["Jet Black"], sizes:["28","30","32","34","36"] },
  { id:"m-denim-5", section:"men", variety:"denim", name:"Weekend Chino", price:1690, mrp:2190, img:"images/m-denim-5.jpg",
    alt:"Jeans hanging on a clothes rack in a store",
    story:"Peached cotton twill with a clean hem, cut to break just once over the shoe. Our answer to the wedding-guest question.",
    spec:[["Fabric","Peached cotton twill"],["Fit","Slim straight"],["Rise","Mid"],["Care","Machine wash cold, warm iron"]],
    colours:["Stone","Fog Grey","Ink"], sizes:["28","30","32","34","36","38"] },

  /* ---------------------------------------------------------- MEN / ETHNIC */
  { id:"m-ethnic-1", section:"men", variety:"ethnic", name:"Ivory Cotton Kurta", price:2490, mrp:3190, img:"images/m-ethnic-1.jpg",
    alt:"Man in an ivory kurta standing against a green wall",
    story:"Handloom cotton with a self-coloured placket. Light enough for a temple morning, formal enough for the reception after.",
    spec:[["Fabric","Handloom cotton"],["Length","Knee, side vents"],["Work","Self-thread placket"],["Care","Gentle machine wash, cool iron"]],
    colours:["Ivory","Sand","Slate"], sizes:["38","40","42","44","46"] },
  { id:"m-ethnic-2", section:"men", variety:"ethnic", name:"Sapphire Silk Sherwani", price:8900, mrp:11500, img:"images/m-ethnic-2.jpg",
    alt:"Man in a blue sherwani standing beside a decorated car",
    story:"Raw silk in a deep sapphire, quilted at the chest so it holds its line all evening. Comes with a matching stole.",
    spec:[["Fabric","Raw silk, cotton lining"],["Work","Tonal thread, quilted chest"],["Includes","Kurta, churidar, stole"],["Care","Dry clean only"]],
    colours:["Sapphire"], sizes:["38","40","42","44","46"], tag:"Made to measure" },
  { id:"m-ethnic-3", section:"men", variety:"ethnic", name:"Rosewood Wedding Sherwani", price:12900, mrp:16900, img:"images/m-ethnic-3.jpg",
    alt:"Man in a maroon and gold embroidered sherwani wearing a turban",
    story:"Six weeks of hand embroidery in gold zari on a rosewood base. The piece we book out first every muhurtham season.",
    spec:[["Fabric","Silk brocade"],["Work","Hand zari, 6 weeks"],["Includes","Sherwani, churidar, dupatta"],["Care","Dry clean only"]],
    colours:["Rosewood","Deep Maroon"], sizes:["38","40","42","44","46"], tag:"Bridal" },
  { id:"m-ethnic-4", section:"men", variety:"ethnic", name:"Zari Bandhgala", price:6900, mrp:8900, img:"images/m-ethnic-4.jpg",
    alt:"Man in traditional embroidered Indian attire with a turban",
    story:"A closed-neck bandhgala with restrained zari at the collar and cuffs. Wear it over a kurta or over trousers.",
    spec:[["Fabric","Silk blend"],["Work","Zari collar and cuff"],["Lining","Full cotton"],["Care","Dry clean only"]],
    colours:["Champagne","Ink"], sizes:["38","40","42","44","46"] },
  { id:"m-ethnic-5", section:"men", variety:"ethnic", name:"Heritage Nehru Set", price:4490, mrp:5690, img:"images/m-ethnic-5.jpg",
    alt:"Man in a traditional sherwani and turban standing outdoors",
    story:"Kurta, churidar and a matched Nehru jacket. The whole set in one bag, which is the reason most people buy it.",
    spec:[["Fabric","Cotton silk"],["Includes","Kurta, churidar, Nehru jacket"],["Work","Plain, tonal buttons"],["Care","Dry clean recommended"]],
    colours:["Oyster","Charcoal"], sizes:["38","40","42","44","46"] },

  /* -------------------------------------------------------- MEN / LAYERING */
  { id:"m-layer-1", section:"men", variety:"layering", name:"Charcoal Wool Blazer", price:6490, mrp:8200, img:"images/m-layer-1.jpg",
    alt:"Man in a black suit jacket and trousers standing outdoors",
    story:"Half-canvas construction in a tropical wool that breathes. Two months of fittings went into this shoulder.",
    spec:[["Fabric","Tropical wool, 240 GSM"],["Build","Half canvas"],["Lining","Half-lined, bemberg"],["Care","Dry clean, steam between wears"]],
    colours:["Charcoal","Ink"], sizes:["38","40","42","44","46"] },
  { id:"m-layer-2", section:"men", variety:"layering", name:"Cobalt Two-Piece", price:7450, mrp:9400, img:"images/m-layer-2.jpg",
    alt:"Man in a blue suit standing on a pavement",
    story:"A suit that photographs well without shouting. Trousers come unhemmed so our tailor can finish them to your shoe.",
    spec:[["Fabric","Wool blend"],["Build","Half canvas, two button"],["Includes","Jacket and trousers"],["Care","Dry clean only"]],
    colours:["Cobalt"], sizes:["38","40","42","44","46"] },
  { id:"m-layer-3", section:"men", variety:"layering", name:"Stone Grey Suit", price:6990, mrp:8900, img:"images/m-layer-3.jpg",
    alt:"Man in a grey suit jacket and black trousers wearing sunglasses",
    story:"Mid-grey, notch lapel, nothing clever. The suit you can wear to an interview, a wedding and a funeral.",
    spec:[["Fabric","Wool polyester blend"],["Build","Fused, structured shoulder"],["Includes","Jacket and trousers"],["Care","Dry clean only"]],
    colours:["Stone Grey"], sizes:["38","40","42","44","46"], tag:"Bestseller" },
  { id:"m-layer-4", section:"men", variety:"layering", name:"Travel Blazer", price:5490, mrp:6900, img:"images/m-layer-4.jpg",
    alt:"Man in a black suit jacket holding a brown leather bag",
    story:"Unstructured, unlined and packable. Roll it into a cabin bag and it comes out looking hung.",
    spec:[["Fabric","Wrinkle-recovering wool blend"],["Build","Unstructured, unlined"],["Pockets","Patch, four internal"],["Care","Steam, dry clean sparingly"]],
    colours:["Ink","Graphite"], sizes:["38","40","42","44"] },
  { id:"m-layer-5", section:"men", variety:"layering", name:"Ink Linen Jacket", price:3990, mrp:4990, img:"images/m-layer-5.jpg",
    alt:"Man in a blue jacket and white dress shirt",
    story:"Pure linen for the six months of the year that punish wool. It will crease. That is the point.",
    spec:[["Fabric","Pure linen"],["Build","Unstructured"],["Lining","Unlined"],["Care","Dry clean, or gentle hand wash"]],
    colours:["Ink","Oat"], sizes:["38","40","42","44","46"] },

  /* ------------------------------------------------------- WOMEN / SAREES */
  { id:"w-saree-1", section:"women", variety:"sarees", name:"Peony Georgette Saree", price:3490, mrp:4490, img:"images/w-saree-1.jpg",
    alt:"Woman in a pink and gold silk saree standing beside a tree",
    story:"Featherweight georgette in blush and blue that drapes without pinning at every pleat. Blouse piece attached.",
    spec:[["Fabric","Pure georgette"],["Length","5.5m with 0.8m blouse piece"],["Border","Tonal satin"],["Care","Dry clean recommended"]],
    colours:["Peony","Powder Blue"], sizes:["Free size"] },
  { id:"w-saree-2", section:"women", variety:"sarees", name:"Amethyst Chiffon Saree", price:3990, mrp:4990, img:"images/w-saree-2.jpg",
    alt:"Woman in a teal and purple silk saree holding a brass lamp",
    story:"A chiffon that falls in long clean lines — the drape most people are actually after when they ask for something light.",
    spec:[["Fabric","Pure chiffon"],["Length","5.5m with blouse piece"],["Border","Fine zari edge"],["Care","Dry clean only"]],
    colours:["Amethyst"], sizes:["Free size"] },
  { id:"w-saree-3", section:"women", variety:"sarees", name:"Morning Cotton Saree", price:2290, mrp:2890, img:"images/w-saree-3.jpg",
    alt:"Woman walking through a park in a saree",
    story:"Handloom cotton for the days a saree has to last from eight in the morning to eight at night. Softens with every wash.",
    spec:[["Fabric","Handloom cotton"],["Length","6.2m with blouse piece"],["Border","Woven contrast"],["Care","Machine wash cold, starch lightly"]],
    colours:["Ecru","Sage","Grey"], sizes:["Free size"], tag:"Everyday" },
  { id:"w-saree-4", section:"women", variety:"sarees", name:"Monochrome Handloom", price:4290, mrp:5490, img:"images/w-saree-4.jpg",
    alt:"Woman wearing a black and white saree",
    story:"Black on white, woven on a pit loom in Chettinad. Our most requested saree from people who claim not to like sarees.",
    spec:[["Fabric","Handloom cotton silk"],["Length","6.2m with blouse piece"],["Weave","Pit loom, Chettinad"],["Care","Dry clean first wash"]],
    colours:["Monochrome"], sizes:["Free size"], tag:"Bestseller" },
  { id:"w-saree-5", section:"women", variety:"sarees", name:"Terracotta Silk Saree", price:6900, mrp:8900, img:"images/w-saree-5.jpg",
    alt:"Woman in a deep red saree with a green border walking along a path",
    story:"Mulberry silk in terracotta with a broad temple border. Weighty in the hand and it shows in the drape.",
    spec:[["Fabric","Mulberry silk"],["Length","6.2m with blouse piece"],["Border","Temple zari, 4in"],["Care","Dry clean only"]],
    colours:["Terracotta"], sizes:["Free size"] },

  /* -------------------------------------------------------- WOMEN / KURTI */
  { id:"w-kurti-1", section:"women", variety:"kurti", name:"Vermillion Cotton Kurta", price:1690, mrp:2190, img:"images/w-kurti-1.jpg",
    alt:"Woman in a red kurta with a floral scarf",
    story:"Straight-cut cotton with deep side slits and pockets that hold a phone. Sold with a matching dupatta.",
    spec:[["Fabric","Cotton cambric"],["Length","46in, side slits"],["Includes","Kurta and dupatta"],["Care","Machine wash cold"]],
    colours:["Vermillion","Indigo"], sizes:["XS","S","M","L","XL","XXL"] },
  { id:"w-kurti-2", section:"women", variety:"kurti", name:"Festive Anarkali Set", price:2790, mrp:3590, img:"images/w-kurti-2.jpg",
    alt:"Woman in red traditional attire holding a handbag",
    story:"A twelve-panel anarkali that moves properly when you walk. Palazzo and dupatta included, so nothing else to match.",
    spec:[["Fabric","Rayon blend"],["Cut","12-panel anarkali"],["Includes","Kurta, palazzo, dupatta"],["Care","Gentle wash, cool iron"]],
    colours:["Ruby","Emerald"], sizes:["XS","S","M","L","XL","XXL"] },
  { id:"w-kurti-3", section:"women", variety:"kurti", name:"Blush Straight Kurta", price:1390, mrp:1790, img:"images/w-kurti-3.jpg",
    alt:"A young woman in a pink outfit sitting outdoors",
    story:"The plainest thing we make and quietly the hardest to get right — the neckline took four samples.",
    spec:[["Fabric","Cotton blend"],["Length","44in"],["Neck","Boat, keyhole back"],["Care","Machine wash cold"]],
    colours:["Blush","Oyster","Fog"], sizes:["XS","S","M","L","XL"] },
  { id:"w-kurti-4", section:"women", variety:"kurti", name:"Rose Chikankari Set", price:2490, mrp:3290, img:"images/w-kurti-4.jpg",
    alt:"Woman in a pink traditional outfit walking with a white bag",
    story:"Hand chikankari from Lucknow on a rose cotton ground. Every panel is slightly different, which is how you know.",
    spec:[["Fabric","Cotton mul"],["Work","Hand chikankari"],["Includes","Kurta and dupatta"],["Care","Hand wash separately"]],
    colours:["Rose","White"], sizes:["S","M","L","XL"], tag:"Handwork" },
  { id:"w-kurti-5", section:"women", variety:"kurti", name:"Indigo Everyday Kurta", price:1190, mrp:1490, img:"images/w-kurti-5.jpg",
    alt:"Smiling woman in a blue dress standing by water",
    story:"Indigo-dyed cotton that fades honestly over a couple of years. Buy two — most people come back for the second.",
    spec:[["Fabric","Indigo-dyed cotton"],["Length","42in"],["Sleeve","Three-quarter"],["Care","Wash cold, separately first three times"]],
    colours:["Indigo"], sizes:["XS","S","M","L","XL","XXL"], tag:"Everyday" },

  /* ------------------------------------------------------- WOMEN / DRESSES */
  { id:"w-dress-1", section:"women", variety:"dresses", name:"Sunlit Midi Dress", price:2290, mrp:2890, img:"images/w-dress-1.jpg",
    alt:"Woman in a light dress walking down a stairway under a blue sky",
    story:"A midi with a self-tie waist that suits far more people than a fixed one. Lined to the knee.",
    spec:[["Fabric","Viscose crepe"],["Length","Midi, 118cm"],["Waist","Self-tie"],["Care","Gentle wash, cool iron"]],
    colours:["Sunlit Cream","Fog"], sizes:["XS","S","M","L","XL"] },
  { id:"w-dress-2", section:"women", variety:"dresses", name:"Ivory Sleeve Midi", price:2590, mrp:3290, img:"images/w-dress-2.jpg",
    alt:"Woman in a white long-sleeve dress wearing sunglasses",
    story:"Long sleeves in a fabric light enough to wear at noon. The compromise our customers kept asking for.",
    spec:[["Fabric","Cotton voile"],["Length","Midi"],["Sleeve","Full, gathered cuff"],["Care","Machine wash cold, hang dry"]],
    colours:["Ivory"], sizes:["XS","S","M","L","XL"] },
  { id:"w-dress-3", section:"women", variety:"dresses", name:"White Column Dress", price:3290, mrp:4190, img:"images/w-dress-3.jpg",
    alt:"A white dress photographed against a plain background",
    story:"One clean vertical line from shoulder to hem, cut in a heavy crepe so it holds the shape. Nothing else needed.",
    spec:[["Fabric","Heavy crepe"],["Length","Column, ankle"],["Lining","Full"],["Care","Dry clean recommended"]],
    colours:["White"], sizes:["XS","S","M","L"], tag:"Occasion" },
  { id:"w-dress-4", section:"women", variety:"dresses", name:"Linen Slip Dress", price:1990, mrp:2490, img:"images/w-dress-4.jpg",
    alt:"Woman in a white dress sitting on a rock",
    story:"Pure linen on a bias cut. It creases within the hour and looks better for it.",
    spec:[["Fabric","Pure linen"],["Cut","Bias, adjustable strap"],["Length","Midi"],["Care","Machine wash cold, dry flat"]],
    colours:["Chalk","Stone"], sizes:["XS","S","M","L","XL"] },
  { id:"w-dress-5", section:"women", variety:"dresses", name:"Seaside Wrap Dress", price:1590, mrp:1990, img:"images/w-dress-5.jpg",
    alt:"Woman walking by the sea holding a woven bag",
    story:"A true wrap with an inner tie, so it stays closed in wind. Our travel dress, and the one we photograph most.",
    spec:[["Fabric","Rayon"],["Cut","Wrap with inner tie"],["Length","Midi"],["Care","Machine wash cold"]],
    colours:["Seaside Blue","Sand"], sizes:["XS","S","M","L","XL"] },

  /* ---------------------------------------------------------- WOMEN / TOPS */
  { id:"w-top-1", section:"women", variety:"tops", name:"Off-Shoulder Poplin Top", price:1290, mrp:1690, img:"images/w-top-1.jpg",
    alt:"Woman in a white off-shoulder top",
    story:"Crisp poplin with an elasticated band that is wide enough not to dig in. Wears well over jeans or a skirt.",
    spec:[["Fabric","Cotton poplin"],["Neck","Off-shoulder, elastic band"],["Length","Cropped"],["Care","Machine wash cold"]],
    colours:["White","Powder"], sizes:["XS","S","M","L","XL"] },
  { id:"w-top-2", section:"women", variety:"tops", name:"Ruby Satin Blouse", price:1690, mrp:2190, img:"images/w-top-2.jpg",
    alt:"Woman in a red blouse wearing a necklace",
    story:"Matte satin, so it reads expensive rather than shiny. Cut with a slightly higher neck for wearing to work.",
    spec:[["Fabric","Matte satin"],["Neck","High round"],["Sleeve","Full, buttoned cuff"],["Care","Hand wash, cool iron"]],
    colours:["Ruby","Ink"], sizes:["XS","S","M","L","XL"] },
  { id:"w-top-3", section:"women", variety:"tops", name:"Co-ord Cotton Shirt", price:1890, mrp:2390, img:"images/w-top-3.jpg",
    alt:"Woman wearing a white shirt and white trousers",
    story:"Buy it with the matching trousers or don't — it works either way, which is why we cut it oversized.",
    spec:[["Fabric","Cotton twill"],["Fit","Oversized"],["Pairs with","Matching wide-leg trouser"],["Care","Machine wash cold"]],
    colours:["White","Fog Grey"], sizes:["XS","S","M","L","XL"] },
  { id:"w-top-4", section:"women", variety:"tops", name:"Teal Tie Blouse", price:1490, mrp:1890, img:"images/w-top-4.jpg",
    alt:"Woman in a teal blouse and black skirt against a red background",
    story:"A neck tie you can knot loose or leave hanging. Small decision, changes the whole outfit.",
    spec:[["Fabric","Viscose georgette"],["Neck","Detachable tie"],["Sleeve","Full"],["Care","Hand wash cold"]],
    colours:["Teal","Bone"], sizes:["XS","S","M","L"] },
  { id:"w-top-5", section:"women", variety:"tops", name:"Linen Sleeveless Top", price:890, mrp:1190, img:"images/w-top-5.jpg",
    alt:"Woman in a white top and linen trousers beside a plant",
    story:"The cheapest thing on this page and the one our staff own in three colours.",
    spec:[["Fabric","Linen cotton blend"],["Neck","Round, wide strap"],["Length","Hip"],["Care","Machine wash cold, dry flat"]],
    colours:["White","Oat","Ash"], sizes:["XS","S","M","L","XL"], tag:"Everyday" },

  /* -------------------------------------------------------- WOMEN / BRIDAL */
  { id:"w-bridal-1", section:"women", variety:"bridal", name:"Crimson Zardozi Lehenga", price:24900, mrp:31500, img:"images/w-bridal-1.jpg",
    alt:"Woman in a red bridal outfit with intricate gold jewellery",
    story:"Four artisans, eleven weeks, and roughly two lakh stitches of zardozi. Fittings begin the day you book.",
    spec:[["Fabric","Silk raw base"],["Work","Hand zardozi, 11 weeks"],["Includes","Lehenga, choli, dupatta"],["Care","Dry clean only, store flat"]],
    colours:["Crimson"], sizes:["Made to measure"], tag:"Bridal" },
  { id:"w-bridal-2", section:"women", variety:"bridal", name:"Gold Kanjivaram Bridal", price:18900, mrp:23900, img:"images/w-bridal-2.jpg",
    alt:"Bride in a gold and peach kanjivaram silk saree",
    story:"Pure kanjivaram silk woven in Kanchipuram with a contrast korvai border. Weighs what a bridal saree should.",
    spec:[["Fabric","Pure kanjivaram silk"],["Weave","Korvai contrast border"],["Zari","Half-fine, tested"],["Care","Dry clean, wrap in muslin"]],
    colours:["Gold Red"], sizes:["Free size"], tag:"Bridal" },
  { id:"w-bridal-3", section:"women", variety:"bridal", name:"Ruby Reception Lehenga", price:16900, mrp:21500, img:"images/w-bridal-3.jpg",
    alt:"Woman in a red and gold bridal outfit",
    story:"Lighter than the wedding piece by nearly two kilos, because nobody should have to sit still at their own reception.",
    spec:[["Fabric","Silk georgette"],["Work","Sequin and thread"],["Includes","Lehenga, choli, dupatta"],["Care","Dry clean only"]],
    colours:["Ruby"], sizes:["S","M","L","XL","Made to measure"] },
  { id:"w-bridal-4", section:"women", variety:"bridal", name:"Temple Border Bridal Saree", price:12900, mrp:16400, img:"images/w-bridal-4.jpg",
    alt:"Woman in a red and gold sari standing outdoors",
    story:"A classical temple border in gold zari on deep red. The saree most of our mothers were married in, made properly again.",
    spec:[["Fabric","Silk"],["Border","Temple zari, 6in"],["Length","6.3m with blouse piece"],["Care","Dry clean only"]],
    colours:["Deep Red"], sizes:["Free size"] },
  { id:"w-bridal-5", section:"women", variety:"bridal", name:"Marigold Silk Lehenga", price:14900, mrp:18900, img:"images/w-bridal-5.jpg",
    alt:"Woman in a red and gold floral outfit seated on a wooden bench",
    story:"Made for the haldi and mehendi days, when red is too much and plain is not enough.",
    spec:[["Fabric","Art silk"],["Work","Gota patti"],["Includes","Lehenga, choli, dupatta"],["Care","Dry clean only"]],
    colours:["Marigold"], sizes:["S","M","L","XL"] },

  /* ----------------------------------------------------------- KIDS / BOYS */
  { id:"k-boy-1", section:"kids", variety:"boys", name:"Little Gentleman Shirt", price:990, mrp:1290, img:"images/k-boy-1.jpg",
    alt:"Boy in a blue shirt and brown trousers standing on grass",
    story:"A proper shirt in miniature — real buttons, a soft interlined collar, and a hem short enough to stay tucked.",
    spec:[["Fabric","Cotton poplin"],["Collar","Soft interlined"],["Fit","Regular"],["Care","Machine wash cold"]],
    colours:["Sky","White"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },
  { id:"k-boy-2", section:"kids", variety:"boys", name:"Monochrome Party Set", price:1290, mrp:1690, img:"images/k-boy-2.jpg",
    alt:"Young boy in a stylish outfit against a dark background",
    story:"Shirt and trousers in the same charcoal, so the whole outfit is one decision on a busy morning.",
    spec:[["Fabric","Cotton blend"],["Includes","Shirt and trouser"],["Fit","Regular"],["Care","Machine wash cold, cool iron"]],
    colours:["Charcoal"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-boy-3", section:"kids", variety:"boys", name:"Twin Floral Shirt", price:890, mrp:1190, img:"images/k-boy-3.jpg",
    alt:"A pair of boys' black and grey floral collared shirts",
    story:"Sold in a two-pack because siblings and cousins are the reason this print exists.",
    spec:[["Fabric","Rayon"],["Includes","Two shirts"],["Collar","Camp"],["Care","Gentle wash, dry in shade"]],
    colours:["Black Floral","Grey Floral"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"], tag:"Two-pack" },
  { id:"k-boy-4", section:"kids", variety:"boys", name:"Picnic Check Shirt", price:790, mrp:990, img:"images/k-boy-4.jpg",
    alt:"Boy in a red, white and blue plaid button-up shirt",
    story:"Yarn-dyed check that survives the wash cycle a school week demands. Elbow seams are double-stitched.",
    spec:[["Fabric","Yarn-dyed cotton check"],["Seams","Double-stitched"],["Fit","Regular"],["Care","Machine wash warm"]],
    colours:["Red Check","Blue Check"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },
  { id:"k-boy-5", section:"kids", variety:"boys", name:"Playground Overshirt", price:1190, mrp:1490, img:"images/k-boy-5.jpg",
    alt:"A young boy standing in front of a graffiti covered wall",
    story:"Heavier than a shirt, lighter than a jacket. Goes over a tee for evening cricket and comes off five minutes later.",
    spec:[["Fabric","Brushed cotton twill"],["Pockets","Two chest, flapped"],["Fit","Relaxed"],["Care","Machine wash cold"]],
    colours:["Olive","Slate"], sizes:["4-5Y","6-7Y","8-9Y","10-11Y"] },

  /* ---------------------------------------------------------- KIDS / GIRLS */
  { id:"k-girl-1", section:"kids", variety:"girls", name:"Daisy White Frock", price:1190, mrp:1490, img:"images/k-girl-1.jpg",
    alt:"Girl in a white dress with a flower headband",
    story:"A white cotton frock with a full skirt and a cotton lining, so nothing scratches at the shoulders.",
    spec:[["Fabric","Cotton poplin, cotton lined"],["Skirt","Full, gathered"],["Closure","Back buttons"],["Care","Machine wash cold"]],
    colours:["White"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-girl-2", section:"kids", variety:"girls", name:"Meadow Day Dress", price:990, mrp:1290, img:"images/k-girl-2.jpg",
    alt:"Girl in a dress reaching towards a flower",
    story:"Two deep pockets, because everything a six-year-old finds outside has to come home with her.",
    spec:[["Fabric","Cotton cambric"],["Pockets","Two, deep"],["Sleeve","Cap"],["Care","Machine wash cold"]],
    colours:["Meadow Green","Sky"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"], tag:"Everyday" },
  { id:"k-girl-3", section:"kids", variety:"girls", name:"Violet Party Frock", price:1590, mrp:1990, img:"images/k-girl-3.jpg",
    alt:"A little girl in a purple dress standing on a red carpet",
    story:"Net over satin with a soft waistband instead of elastic that leaves a mark. Made for birthday photographs.",
    spec:[["Fabric","Net over satin"],["Waist","Soft banded"],["Closure","Back zip"],["Care","Hand wash, dry flat"]],
    colours:["Violet"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-girl-4", section:"kids", variety:"girls", name:"Peony Pink Frock", price:1290, mrp:1590, img:"images/k-girl-4.jpg",
    alt:"A little girl in a pink dress posing for a picture",
    story:"Pink without glitter, tulle or a licensed character on it. Harder to find than it should be.",
    spec:[["Fabric","Cotton blend"],["Skirt","A-line"],["Closure","Back buttons"],["Care","Machine wash cold"]],
    colours:["Peony"], sizes:["2-3Y","4-5Y","6-7Y"] },
  { id:"k-girl-5", section:"kids", variety:"girls", name:"Bluebell Twirl Dress", price:1090, mrp:1390, img:"images/k-girl-5.jpg",
    alt:"A little girl in a blue dress posing",
    story:"Cut on a circle so it spins properly. We tested it on the shop floor with four children and a stopwatch.",
    spec:[["Fabric","Cotton voile"],["Skirt","Circle cut"],["Sleeve","Puff"],["Care","Machine wash cold, dry in shade"]],
    colours:["Bluebell"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },

  /* ----------------------------------------------------------- KIDS / TEES */
  { id:"k-tee-1", section:"kids", variety:"tees", name:"Blank Slate Tee", price:390, mrp:490, img:"images/k-tee-1.jpg",
    alt:"A plain white crew neck t-shirt",
    story:"Plain white, pre-shrunk, sold in singles or fives. The school-holiday workhorse.",
    spec:[["Fabric","180 GSM cotton, pre-shrunk"],["Neck","Ribbed crew"],["Fit","Regular"],["Care","Machine wash warm"]],
    colours:["White","Grey Melange"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"], tag:"Everyday" },
  { id:"k-tee-2", section:"kids", variety:"tees", name:"Seaside Blue Tee", price:490, mrp:590, img:"images/k-tee-2.jpg",
    alt:"Boy in a blue crew neck t-shirt on a beach",
    story:"Colour-fast blue that comes back from a beach day the same shade it went out.",
    spec:[["Fabric","190 GSM cotton"],["Neck","Ribbed crew"],["Fit","Regular"],["Care","Machine wash cold"]],
    colours:["Seaside Blue"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-tee-3", section:"kids", variety:"tees", name:"Pocket Play Tee", price:450, mrp:590, img:"images/k-tee-3.jpg",
    alt:"Boy standing with his hand in his pocket during the day",
    story:"One chest pocket, reinforced at both corners, because that is where the pulling happens.",
    spec:[["Fabric","190 GSM cotton"],["Pocket","Chest, bar-tacked"],["Fit","Regular"],["Care","Machine wash warm"]],
    colours:["Sand","Ash"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },
  { id:"k-tee-4", section:"kids", variety:"tees", name:"Weekend Tee & Shorts", price:690, mrp:890, img:"images/k-tee-4.jpg",
    alt:"Girl in a black and white t-shirt and white shorts",
    story:"Tee and shorts together for the price most places charge for the tee. Both wash at the same temperature.",
    spec:[["Fabric","Cotton jersey"],["Includes","Tee and shorts"],["Waist","Soft elastic, drawcord"],["Care","Machine wash warm"]],
    colours:["Monochrome"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"], tag:"Set" },
  { id:"k-tee-5", section:"kids", variety:"tees", name:"Ink Black Tee", price:490, mrp:590, img:"images/k-tee-5.jpg",
    alt:"A young boy wearing a black t-shirt",
    story:"Black, which hides more than any parent will admit to needing it to.",
    spec:[["Fabric","190 GSM cotton"],["Neck","Ribbed crew"],["Fit","Regular"],["Care","Wash cold with darks"]],
    colours:["Ink"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },

  /* --------------------------------------------------------- KIDS / ETHNIC */
  { id:"k-ethnic-1", section:"kids", variety:"ethnic", name:"Little Rani Lehenga", price:1990, mrp:2490, img:"images/k-ethnic-1.jpg",
    alt:"A young girl in a red and gold dress",
    story:"A proper lehenga scaled down, with the waist on soft elastic so it can be worn for a whole reception.",
    spec:[["Fabric","Art silk"],["Waist","Soft elastic"],["Includes","Lehenga, choli, dupatta"],["Care","Dry clean recommended"]],
    colours:["Red Gold"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"], tag:"Festive" },
  { id:"k-ethnic-2", section:"kids", variety:"ethnic", name:"Marigold Festive Frock", price:1490, mrp:1890, img:"images/k-ethnic-2.jpg",
    alt:"Girl in a red and yellow dress holding a bouquet of yellow flowers",
    story:"Festive without being formal — this one gets worn to the function and then to school-day fancy dress.",
    spec:[["Fabric","Cotton silk"],["Lining","Full cotton"],["Closure","Back tie"],["Care","Gentle wash, dry in shade"]],
    colours:["Marigold"], sizes:["2-3Y","4-5Y","6-7Y"] },
  { id:"k-ethnic-3", section:"kids", variety:"ethnic", name:"Sunburst Pattu Pavadai", price:1690, mrp:2190, img:"images/k-ethnic-3.jpg",
    alt:"Girl in a yellow and red traditional dress sitting outdoors",
    story:"The traditional pattu pavadai with a zari border, lined in cotton so a Chennai September is survivable.",
    spec:[["Fabric","Art silk, cotton lined"],["Border","Zari"],["Includes","Pavadai and blouse"],["Care","Dry clean recommended"]],
    colours:["Sunburst"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-ethnic-4", section:"kids", variety:"ethnic", name:"Ruby Diwali Set", price:1290, mrp:1690, img:"images/k-ethnic-4.jpg",
    alt:"Girl in a red long sleeve dress seated on a wooden bench",
    story:"Made for the one evening a year when there is no time to hunt for something that fits.",
    spec:[["Fabric","Cotton silk"],["Sleeve","Full"],["Lining","Cotton"],["Care","Gentle wash"]],
    colours:["Ruby"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-ethnic-5", section:"kids", variety:"ethnic", name:"Twin Festive Set", price:990, mrp:1290, img:"images/k-ethnic-5.jpg",
    alt:"Two young girls in traditional Indian clothing",
    story:"Two matching sets at one price, sized independently — the request we hear most from families with two.",
    spec:[["Fabric","Cotton blend"],["Includes","Two sets, sizes chosen separately"],["Lining","Cotton"],["Care","Machine wash cold"]],
    colours:["Assorted"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"], tag:"Two-pack" },

  /* --------------------------------------------------------- KIDS / WINTER */
  { id:"k-winter-1", section:"kids", variety:"winter", name:"Heart Knit Sweater", price:1190, mrp:1490, img:"images/k-winter-1.jpg",
    alt:"Girl in a white and pink heart print sweater",
    story:"Cotton-rich knit rather than wool, so it can be worn against skin without a vest underneath.",
    spec:[["Fabric","Cotton-rich knit"],["Neck","Ribbed round"],["Weight","Mid"],["Care","Hand wash, dry flat"]],
    colours:["White Pink"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-winter-2", section:"kids", variety:"winter", name:"Hill Station Jacket", price:1690, mrp:2190, img:"images/k-winter-2.jpg",
    alt:"A young boy wearing a jacket and a hat",
    story:"Enough padding for Ooty in December and not a gram more. Zips have a chin guard at the top.",
    spec:[["Fabric","Nylon shell, poly fill"],["Zip","Full, chin guard"],["Hood","Detachable"],["Care","Machine wash cold, tumble low"]],
    colours:["Slate","Navy"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },
  { id:"k-winter-3", section:"kids", variety:"winter", name:"Sunbeam Puffer", price:1590, mrp:1990, img:"images/k-winter-3.jpg",
    alt:"Boy in a black and yellow jacket and knit cap",
    story:"Bright on purpose. Easier to spot in a crowd, which is the actual feature.",
    spec:[["Fabric","Poly shell, quilted fill"],["Zip","Full"],["Pockets","Two, zipped"],["Care","Machine wash cold"]],
    colours:["Sunbeam"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y"] },
  { id:"k-winter-4", section:"kids", variety:"winter", name:"Marigold Zip Jacket", price:1390, mrp:1790, img:"images/k-winter-4.jpg",
    alt:"Boy in a yellow zip-up jacket",
    story:"A light zip-through for the shoulder months, when a sweater is too much by nine in the morning.",
    spec:[["Fabric","Fleece-backed jersey"],["Zip","Full"],["Fit","Regular"],["Care","Machine wash cold"]],
    colours:["Marigold","Grey"], sizes:["2-3Y","4-5Y","6-7Y","8-9Y","10-11Y"] },
  { id:"k-winter-5", section:"kids", variety:"winter", name:"Cloud Knit Cap Set", price:890, mrp:1190, img:"images/k-winter-5.jpg",
    alt:"Girl in a grey and blue knit cap smiling",
    story:"Cap and mittens on a cord, so only one of the two can be lost at a time.",
    spec:[["Fabric","Acrylic cotton knit"],["Includes","Cap and mittens"],["Cord","Attached"],["Care","Hand wash"]],
    colours:["Cloud Grey","Blue"], sizes:["2-4Y","5-8Y","9-12Y"] }
];
